### ISSUE TITLE
Extensions are not installed

### ISSUE THREAD

**Issue by Cris70** [qcerasmus/notepadqq-extensions#1]
Hi, I wanted to try out your extensions. So I downloaded the two .nqqext files, then in Notepadqq I selected Extensions -> Install Extension... from the main menu.
The extensions were installed correctly according to Notepadqq, but in the Extensions menu I do not see anything, even after restarting Notepadqq.
Did I do something wrong?

**Comment by Cris70** [comment]
Here is the output from the two installations, just in case...
[install1.txt](https://github.com/qcerasmus/notepadqq-extensions/files/1964097/install1.txt)
[install2.txt](https://github.com/qcerasmus/notepadqq-extensions/files/1964098/install2.txt)

**Comment by qcerasmus** [comment]
Hi,

As far as I can tell you didn't do anything wrong. Out of interest, are you building NotepadQQ from source or did you install via some package manager?

We might be able to put some extra logging in to ensure notepadqq is finding those extensions.

**Comment by Cris70** [comment]
Hi @qcerasmus , I installed from openSUSE main repository. Installed release is v1.3.6.
I'm on openSUSE Tumbleweed.

**Comment by qcerasmus** [comment]
I'm currently running version 1.4.2 . I wonder if that could make a difference.

**Comment by Cris70** [comment]
Yes, I think so. I'll wait for the openSUSE package maintainers to update the package. Or maybe I'll ping them over that.
Thank you!

**Comment by qcerasmus** [comment]
No problem :) I'll leave the issue open incase that doesn't fix it.

**Comment by Cris70** [comment]
Hi, I am using v1.4.0 now and installation works! However, I have another problem now, but I don't know if it depends from the extensions or from the editor itself. When I install your extensions, I get the message "Unsupported runtime".

**Comment by sharpensteel** [comment]
Hi, i have same problem:
`The extensions were installed correctly according to Notepadqq, but in the Extensions menu I do not see anything, even after restarting Notepadqq.`
[install log](https://github.com/qcerasmus/notepadqq-extensions/files/2045735/install.log)
Notepadqq v1.4.2, ubuntu 18, nodejs v.10

what could it be?

**Comment by qcerasmus** [comment]
I've opened a ticket on NotepaddQQ project, because I'm not sure what is happening.
Sorry guys :)

**Comment by Cris70** [comment]
@qcerasmus np ;-)
I'll be monitoring the ticket on the Notepadqq project.
Thank you!

**Comment by JReming85** [comment]
@sharpensteel I think I know why its not working for you.

Do you have it linked to the correct version of node & npm?

Latest version available in Ubuntu Repo is 4.2.6
LTS Node is 10.15.0
Lastest Node is 11.6.0

Latest version supported by Notepadqq is 0.12 - https://nodejs.org/dist/v0.12.0/node-v0.12.0-linux-x64.tar.gz


Try downloading 0.12 and linking it to that and see if it works

*Note* It should work with any version 6.4 or older as well
